version: '3.8'

services:
  home:
    build:
      context: ./home
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=home:app
      - PYTHONPATH=/app
    networks:
      - flask-network
    command: flask run --host=0.0.0.0 --port=5002

  logeo:
    build: 
      context: ./logeo
    ports:
      - "5003:5003"
    environment:
      - FLASK_APP=registro:app
      - PYTHONPATH=/app
    networks:
      - flask-network
    command: flask run --host=0.0.0.0 --port=5003

networks:
  flask-network:
    driver: bridge
