version: '3'

services:
  inicio:
    build: ./home
    ports:
      - "5001:5000"
    volumes:
      - ./home:/usr/src/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  vendedor:
    build: ./VistaVendedor
    ports:
      - "5002:5000"
    volumes:
      - ./VistaVendedor:/usr/src/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  comprador:
    build: ./VistaComprador
    ports:
      - "5003:5000"
    volumes:
      - ./VistaComprador:/usr/src/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  admin:
    build: ./VistaAdministrador
    ports:
      - "5004:5000"
    volumes:
      - ./VistaAdministrador:/usr/src/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mi_base_de_datos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
