version: '3'

services:
  inicio:
    build: ./home
    ports:
      - "5001:5000"
    volumes:
      - ./home:/usr/src/app
    env_file:
      - ./database_postgresql/inicio.env
    environment:
      - FLASK_ENV=development
    depends_on:
      - db_inicio

  vendedor:
    build: ./VistaVendedor
    ports:
      - "5002:5000"
    volumes:
      - ./VistaVendedor:/usr/src/app
    env_file:
      - ./database_postgresql/vendedor.env
    environment:
      - FLASK_ENV=development
    depends_on:
      - db_vendedor

  comprador:
    build: ./VistaComprador
    ports:
      - "5003:5000"
    volumes:
      - ./VistaComprador:/usr/src/app
    env_file:
      - ./database_postgresql/comprador.env
    environment:
      - FLASK_ENV=development
    depends_on:
      - db_comprador

  admin:
    build: ./VistaAdministrador
    ports:
      - "5004:5000"
    volumes:
      - ./VistaAdministrador:/usr/src/app
    env_file:
      - ./database_postgresql/admin.env
    environment:
      - FLASK_ENV=development
    depends_on:
      - db_admin

  db_inicio:
    image: postgres:latest
    env_file:
      - ./database_postgresql/inicio.env
    volumes:
      - inicio_data:/var/lib/postgresql/data
      - ./database_postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  db_comprador:
    image: postgres:latest
    env_file:
      - ./database_postgresql/comprador.env
    volumes:
      - comprador_data:/var/lib/postgresql/data

  db_vendedor:
    image: postgres:latest
    env_file:
      - ./database_postgresql/vendedor.env
    volumes:
      - vendedor_data:/var/lib/postgresql/data

  db_admin:
    image: postgres:latest
    env_file:
      - ./database_postgresql/admin.env
    volumes:
      - admin_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db_inicio

volumes:
    inicio_data:
    admin_data:
    comprador_data:
    vendedor_data:
