services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.dev
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    depends_on:
      - postgres

  home:
    build: ./home
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: home.py
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URL: postgresql://root:root@postgres:5432/root
    depends_on:
      - postgres


  # VistaAdministrador:
  #   build: ./VistaAdministrador
  #   ports:
  #     - "5001:5000"
  #   environment:
  #     DATABASE_URL: postgres://admin_user:admin_password@database_admin:5432/admin_database
  #   depends_on:
  #     - database_admin

  # VistaComprador:
  #   build: ./VistaComprador
  #   ports:
  #     - "5002:5000"
  #   environment:
  #     DATABASE_URL: postgres://comprador_user:comprador_password@database_comprador:5432/comprador_database
  #   depends_on:
  #     - database_comprador

  # VistaVendedor:
  #   build: ./VistaVendedor
  #   ports:
  #     - "5003:5000"
  #   environment:
  #     DATABASE_URL: postgres://vendedor_user:vendedor_password@database_vendedor:5432/vendedor_database
  #   depends_on:
  #     - database_vendedor

  